# SPRING CONFIGURATION:
server:
  port: 8081

# SLF4J LOGGING CONFIGURATION:
#logging:
#  level:
#    root: trace

# POSTGRESQL DATABASE CONFIGURATION:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/images_api
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    #  security:
    #    user:
    #      name: hieu
    #      password: hieu
    servlet:
      multipart:
        enabled: true
        max-file-size: 5MB
        max-request-size: 5MB
  profiles:
    active: