# SLF4J LOGGING CONFIGURATION:
#logging:
#  level:
#    root: trace


# H2 DATABASE CONFIGURATION:
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:images_api
#    username: sa
#    password: # Enter your H2 database password
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    servlet:
#      multipart:
#        enabled: true
#        max-file-size: 5MB
#        max-request-size: 5MB
#  profiles:
#    active:


# POSTGRESQL DATABASE CONFIGURATION:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/images_api
    username: postgres
    password: postgres
    initialization-mode: always
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#  security:
#    user:
#      name: hieu
#      password: hieu
    servlet:
      multipart:
        enabled: true
        max-file-size: 5MB
        max-request-size: 5MB
  profiles:
    active:
  # REDIS configuration to use Redis as a caching database:
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true
  # REDIS configuration to use Redis as a NoSQL database:
#  redis:
#    host: localhost
#      password:
#      port: 6379
#      lettuce:
#        shutdown-timeout: 30000
#        pool:
#          # Connection pool maximum connections (negative for no limit) (default value is 8)
#          max-active: 30
#          # Maximum free connections in connection pool (default value is 8)
#          max-idle: 8
#          # Minimum free connections in connection pool (default value is 0)
#          min-idle: 0


# MYSQL DATABASE CONFIGURATION:
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/images_api
#    username: root
#    password: # Enter your MySQL database password.
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL57Dialect
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#    #  security:
#    #    user:
#    #      name: hieu
#    #      password: hieu
#    servlet:
#      multipart:
#        enabled: true
#        max-file-size: 5MB
#        max-request-size: 5MB
#  profiles:
#    active:
##   REDIS configuration to use Redis as a caching database:
##  cache:
##    type: redis
##    redis:
##      time-to-live: 60000
##      cache-null-values: true
##   REDIS configuration to use Redis as a NoSQL database:
##  redis:
##    host: localhost
##      password:
##      port: 6379
##      lettuce:
##        shutdown-timeout: 30000
##        pool:
##          # Connection pool maximum connections (negative for no limit) (default value is 8)
##          max-active: 30
##          # Maximum free connections in connection pool (default value is 8)
##          max-idle: 8
##          # Minimum free connections in connection pool (default value is 0)
##          min-idle: 0